// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Convert(arg1:Array<string>,arg2:string,arg3:string,arg4:boolean):Promise<Array<main.ConversionResult>>;

export function OpenFile(arg1:string):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;
